format_version: 10
pipelines:
  todo-build:
    group: defaultGroup
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-repo:
        git: https://github.com/Afk-Akash/todo
        shallow_clone: false
        auto_update: true
        branch: master
    stages:
    - build:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          build-publish:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - dockerize
                command: make
                run_if: passed
            - exec:
                arguments:
                - publish
                command: make
                run_if: passed
