format_version: 10
pipelines:
  7thPipeline-code:
    group: defaultGroup
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-ce2dbe1:
        git: https://github.com/Afk-Akash/todo
        shallow_clone: false
        auto_update: true
        branch: master
    stages:
    - build-react-app:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          install-node-modules:
            timeout: 0
            tasks:
            - exec:
                command: pwd
                run_if: passed
            - exec:
                arguments:
                - install
                command: npm
                run_if: passed
