format_version: "3"

pipelines:
  dockerize-and-publish:
    group: "Docker"
    label_template: "dockerize-and-publish-$(COUNT)"
    lock_behavior: none
    materials:
      git-repo:
        git: "https://github.com/Afk-Akash/todo"
        branch: "master"
    stages:
      - build:
          clean_workspace: true
          jobs:
            - build-and-publish-docker-image:
                environment_variables:
                  DOCKER_HUB_USERNAME: "your_username"
                  DOCKER_HUB_PASSWORD: "your_password"
                tasks:
                  - exec:
                      command: make
                      arguments:
                        - dockerize
                      run_if: passed
                  - exec:
                      command: make
                      arguments:
                        - publish
                      run_if: passed
